/**
 * RAM-0 measurement runner (instrument, NO secrets).
 *
 * Drives `ram-probe.ts` across the account-free cohort matrix with the RAM-0
 * protocol guarantees the audit (§RAM-0) requires: ≥3 repetitions, median +
 * range, and a COUNTERBALANCED run order (condition order is rotated per rep so
 * machine-pressure drift does not systematically bias one condition). Each run
 * is an isolated child process (`ram-probe.ts`) that spawns exactly one sidecar,
 * so one crashed run never poisons the rest, and every sidecar PID is
 * independently kill-verified.
 *
 * Conditions (all real-engine + attached; corpora pre-generated by
 * `ram-corpus-gen.ts`):
 *   - enrich50    : 50-session corpus,  MIMALLOC default   (enrich-volume LOW)
 *   - enrich600   : 600-session corpus, MIMALLOC default   (enrich-volume HIGH)
 *   - mimalloc0   : 600-session corpus, MIMALLOC_PURGE_DELAY=0  (A/B vs enrich600)
 * Plus a boot-floor-only run (no attach, empty corpus) for the pure floor.
 *
 * NOTE on the enrich A/B: the enrich limit `SESSIONS_CATALOG_ENRICH_LIMIT`
 * (`app/sidecar/sessionsCatalogDomain.ts:62`) is a module const, not env-driven,
 * and enumeration enriches min(limit, discovered). We therefore realize
 * "enrich=50" vs "enrich=600" by CORPUS SIZE at the fixed shipping limit of 600
 * — no engine-behavior edit. This measures enrichment VOLUME cost (the audit's
 * 278 vs 467 question). The strict interim-knob A/B (limit varied on a fixed
 * large corpus) additionally needs a source test-seam and is PARKED.
 *
 * Usage:
 *   bun run app/scripts/ram-measure.ts --out <dir> --reps 3 \
 *     --corpus50 <dir> --corpus600 <dir> --empty <dir> \
 *     --dwell-ms 240000 --sample-ms 30000
 */

import { spawnSync } from 'node:child_process'
import { mkdirSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

import { parseArgs } from './ramInstrument.js'

const here = dirname(fileURLToPath(import.meta.url))
const PROBE = join(here, 'ram-probe.ts')

type Cond = {
  name: string
  configDir: string
  attach: boolean
  mimalloc?: string
}

type ProbeResult = {
  label: string
  reachedReady: boolean
  killVerified: boolean
  survivors: number[]
  samples: Array<{ label: string; elapsedMs: number; rssMB: number | null; footprintMB: number | null; footprintPeakMB: number | null }>
}

function median(xs: number[]): number {
  const s = [...xs].filter(x => Number.isFinite(x)).sort((a, b) => a - b)
  if (s.length === 0) return NaN
  const mid = Math.floor(s.length / 2)
  return s.length % 2 ? s[mid] : +((s[mid - 1] + s[mid]) / 2).toFixed(1)
}

function rotate<T>(arr: T[], n: number): T[] {
  const k = ((n % arr.length) + arr.length) % arr.length
  return [...arr.slice(k), ...arr.slice(0, k)]
}

function main(): void {
  const args = parseArgs(process.argv.slice(2))
  // Inside the app package, where .gitignore covers .ram-scratch/ whatever cwd
  // the runner was invoked from (the documented usage runs it from the repo root).
  const outDir = args.out ?? join(here, '..', '.ram-scratch', 'measure')
  const reps = Number(args.reps ?? '3')
  const dwellMs = args['dwell-ms'] ?? '240000'
  const sampleMs = args['sample-ms'] ?? '30000'
  const corpus50 = args.corpus50
  const corpus600 = args.corpus600
  const empty = args.empty
  if (!corpus50 || !corpus600 || !empty) {
    process.stderr.write('ram-measure: --corpus50 --corpus600 --empty are required\n')
    process.exit(2)
  }
  mkdirSync(outDir, { recursive: true })

  const conds: Cond[] = [
    { name: 'enrich50', configDir: corpus50, attach: true },
    { name: 'enrich600', configDir: corpus600, attach: true },
    { name: 'mimalloc0', configDir: corpus600, attach: true, mimalloc: '0' },
  ]
  // Boot-floor-only run (no attach, empty corpus) once per rep, first.
  const bootCond: Cond = { name: 'bootfloor', configDir: empty, attach: false }

  const runOrder: Array<{ rep: number; cond: Cond }> = []
  for (let r = 0; r < reps; r++) {
    runOrder.push({ rep: r, cond: bootCond })
    for (const c of rotate(conds, r)) runOrder.push({ rep: r, cond: c })
  }

  const results: Array<{ rep: number; cond: string; result: ProbeResult }> = []
  for (const { rep, cond } of runOrder) {
    const label = `${cond.name}-r${rep}`
    const probeArgs = [
      'run', PROBE,
      '--config-dir', cond.configDir,
      '--label', label,
      '--out', outDir,
      '--mode', 'real',
      '--dwell-ms', cond.attach ? dwellMs : '5000',
      '--sample-ms', sampleMs,
    ]
    if (cond.attach) probeArgs.push('--attach', 'true')
    if (cond.mimalloc !== undefined) probeArgs.push('--mimalloc-purge-delay', cond.mimalloc)
    process.stderr.write(`\n=== RUN ${label} (order ${results.length + 1}/${runOrder.length}) ===\n`)
    const res = spawnSync('bun', probeArgs, { encoding: 'utf8', maxBuffer: 32 * 1024 * 1024 })
    if (res.status !== 0) {
      process.stderr.write(`run ${label} FAILED (exit ${res.status})\n${res.stderr}\n`)
      results.push({ rep, cond: cond.name, result: { label, reachedReady: false, killVerified: false, survivors: [], samples: [] } })
      continue
    }
    try {
      const parsed = JSON.parse(res.stdout) as ProbeResult
      results.push({ rep, cond: cond.name, result: parsed })
    } catch {
      process.stderr.write(`run ${label}: could not parse probe JSON\n${res.stdout.slice(-500)}\n`)
    }
  }

  // Aggregate: boot footprint/RSS = 'boot' sample; plateau = last attached sample.
  const byCond: Record<string, ProbeResult[]> = {}
  for (const { cond, result } of results) (byCond[cond] ??= []).push(result)

  const agg: Record<string, unknown> = {}
  for (const [name, rs] of Object.entries(byCond)) {
    const boot = rs.map(r => r.samples.find(s => s.label === 'boot'))
    const plateau = rs.map(r => {
      const attached = r.samples.filter(s => s.label.startsWith('attached'))
      return attached.length ? attached[attached.length - 1] : undefined
    })
    const num = (xs: Array<number | null | undefined>) => xs.filter((x): x is number => typeof x === 'number')
    agg[name] = {
      reps: rs.length,
      // Attempted (reps) vs runs that produced usable samples (review F3): a
      // failed/leaked run is counted in `reps` but excluded from `validReps` and
      // from the medians below, so `reps: 3` never implies a 3-observation median.
      validReps: rs.filter(r => r.reachedReady && r.killVerified && r.samples.length > 0).length,
      allKillVerified: rs.every(r => r.killVerified),
      allReady: rs.every(r => r.reachedReady),
      boot: {
        rssMB: { median: median(num(boot.map(b => b?.rssMB))), values: num(boot.map(b => b?.rssMB)) },
        footprintMB: { median: median(num(boot.map(b => b?.footprintMB))), values: num(boot.map(b => b?.footprintMB)) },
      },
      plateau: {
        rssMB: { median: median(num(plateau.map(p => p?.rssMB))), values: num(plateau.map(p => p?.rssMB)) },
        footprintMB: { median: median(num(plateau.map(p => p?.footprintMB))), values: num(plateau.map(p => p?.footprintMB)) },
      },
    }
  }

  const summary = {
    runner: 'app/scripts/ram-measure.ts',
    reps,
    dwellMs: Number(dwellMs),
    sampleMs: Number(sampleMs),
    runOrder: runOrder.map(o => `${o.cond.name}-r${o.rep}`),
    corpus50, corpus600, empty,
    aggregate: agg,
    runs: results.map(r => ({ rep: r.rep, cond: r.cond, killVerified: r.result.killVerified, reachedReady: r.result.reachedReady, samples: r.result.samples })),
  }
  writeFileSync(join(outDir, 'ram0-aggregate.json'), JSON.stringify(summary, null, 2) + '\n')
  process.stdout.write(JSON.stringify(summary, null, 2) + '\n')
}

main()
