import { afterAll, afterEach, beforeAll, expect, test } from 'bun:test';
import { act } from 'react';
import { createDomTestHarness, type DomTestHarness } from './domTestHarness.js';
import { UsagePage } from './UsagePage.js';
import { collectRetainedUsage } from '../../../src/utils/statsUsage.js';
let harness: DomTestHarness;
beforeAll(async () => { harness = await createDomTestHarness(); });
afterEach(async () => { await harness.unmountAll(); });
afterAll(async () => { await harness.teardown(); });
test('range controls and chart keyboard selection expose matching UTC values without a session', async () => {
    const snapshot = await collectRetainedUsage([], '2026-09-13T12:00:00.000Z');
    const tree = await harness.mount(<UsagePage state={{ snapshot, status: 'ready' }}/>);
    const button = Array.from(tree.container.querySelectorAll('button')).find(b => b.textContent === '30 days')!;
    await act(async () => button.click());
    expect(button.getAttribute('aria-pressed')).toBe('true');
    expect(tree.container.textContent).toContain('2026-08-15 to 2026-09-13');
    const day = tree.container.querySelector('g[role="button"]')!;
    await act(async () => day.dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', bubbles: true })));
    expect(tree.container.querySelector('.usage-day-readout')?.textContent).toContain('2026-08-15');
    expect(tree.container.querySelector('details summary')?.textContent).toBe('Accessible values table');
    expect(tree.container.querySelectorAll('table')[0]?.querySelectorAll('tbody tr')).toHaveLength(30);
});

test('heatmap keyboard selection, error modes, and donut highlighting expose recorded values', async () => {
    const snapshot = await collectRetainedUsage([], '2026-09-13T12:00:00.000Z');
    const summary = snapshot.ranges['7d'];
    summary.days[0]!.hourlyRequests[1] = 4;
    summary.tools = [{ id: 'bash', kind: 'named', label: 'Bash', requests: 10, results: 8, errors: 2 }, { id: 'read', kind: 'named', label: 'Read', requests: 2, results: 1, errors: 1 }];
    summary.models = [{ id: 'a', kind: 'named', label: 'Model A', tokens: { fresh: 10, read: 0, write: 0, output: 0 } }, { id: 'b', kind: 'named', label: 'Model B', tokens: { fresh: 20, read: 0, write: 0, output: 0 } }];
    summary.tokens.fresh = 30;
    const tree = await harness.mount(<UsagePage state={{ snapshot, status: 'ready' }}/>);
    const cells = tree.container.querySelectorAll('.usage-heatmap g[role="button"]');
    expect(cells).toHaveLength(168);
    expect(tree.container.querySelectorAll('.usage-heatmap [tabindex="0"]')).toHaveLength(1);
    await act(async () => cells[0]!.dispatchEvent(new KeyboardEvent('keydown', { key: 'ArrowRight', bubbles: true })));
    expect(cells[7]!.getAttribute('tabindex')).toBe('0');
    await act(async () => cells[7]!.dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', bubbles: true })));
    expect(tree.container.querySelector('.usage-day-readout')?.textContent).toContain('2026-09-07');
    expect(tree.container.querySelector('.usage-heatmap')?.textContent).toContain('4 tool requests');
    const errorRows = () => Array.from(tree.container.querySelectorAll<HTMLButtonElement>('.usage-error-row'));
    expect(errorRows()[0]!.textContent).toContain('Bash');
    await act(async () => Array.from(tree.container.querySelectorAll('button')).find(b => b.textContent === 'Rate')!.click());
    expect(errorRows()[0]!.textContent).toContain('Read');
    await act(async () => errorRows()[1]!.click());
    expect(tree.container.textContent).toContain('6 successful · 2 errors · 2 without a matched result');
    await act(async () => tree.container.querySelector<HTMLButtonElement>('.usage-model-key button')!.click());
    expect(tree.container.querySelector('.usage-donut-total')?.textContent).toBe('10');
    expect(tree.container.querySelectorAll('.usage-model-muted').length).toBeGreaterThan(0);
});
