import { FILE_PATCH_TOOL_NAME } from './constants.js'

export function getFilePatchToolDescription(): string {
  return [
    '## `Apply_patch`',
    '',
    'Use the `Apply_patch` tool to edit files.',
    '',
    'Apply file edits with this envelope:',
    '',
    '*** Begin Patch',
    '[ one or more file sections ]',
    '*** End Patch',
    '',
    'Use exactly one operation for each affected source path. Keep all source paths',
    'and move destinations disjoint. Do not make operations depend on earlier',
    'operations, chain moves, swap paths, or repeat a path.',
    '',
    '*** Add File: <path> - create a new file. Every following line is a + line (the initial contents).',
    '*** Delete File: <path> - remove an existing file. Nothing follows.',
    '*** Update File: <path> - patch an existing file in place (optionally with a rename).',
    '',
    'An update may be followed immediately by "*** Move to: <new path>".',
    'Put update hunks in file order. Each hunk starts with "@@" and contains:',
    '',
    '- Context lines start with a space.',
    '- Deleted lines start with "-".',
    '- Added lines start with "+".',
    '- A hunk must match exactly one eligible consecutive ordered run in the current file.',
    '- Any non-empty text after "@@" is a mandatory textual scope constraint. It must',
    '  identify the scope containing the hunk. It is not a fallback hint.',
    '- Include enough literal surrounding context to make the run unique. Do not',
    '  rely on semantic or reflow matching.',
    '- Use "*** End of File" after a hunk that appends at the file end.',
    '- Use "\\ No newline at end of file" when the affected file has no final newline.',
    '',
    'For example:',
    '',
    '*** Begin Patch',
    '*** Update File: src/app.ts',
    '@@ function greet() {',
    "-  return 'hello'",
    "+  return 'hi'",
    ' }',
    '*** End Patch',
    '',
    'Rules for execution:',
    '',
    '- Patch paths resolve relative to the current session working directory.',
    '  Use relative paths, never absolute.',
    '- Updates use the current file snapshot at execution time. A unique valid',
    '  current match is authoritative even if an earlier Read is stale or absent.',
    '- A bare Delete File requires a complete, unbounded model-visible Read first.',
    '- Apply_patch preflights every independent operation in memory. If any',
    '  operation fails, it writes nothing. Independent failures are reported',
    '  together, with a bounded list of repair details.',
    '- Preflight does not make multi-file writes crash-atomic or prevent',
    '  concurrent external changes.',
  ].join('\n')
}

export { FILE_PATCH_TOOL_NAME }
